AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-getfeed

  Sample SAM Template for lambda-getfeed

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: beta

  GetFeedFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 60 # Seconds before lambda function timesout
      Architectures:
        - x86_64
      Events:
        GetFeedHttpApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getfeed
            Method: get
            ApiId:
              Ref: HttpApi
